/**
 * @renpy-ui/codegen
 *
 * Deterministic spec -> .rpy emitter. Pure TS; no DOM dependencies.
 * See ARCHITECTURE.md §5 for the pipeline and graph-to-block algorithm.
 *
 * Stub in M0; real emitters land in M1.
 */

import { SPEC_VERSION } from '@renpy-ui/spec';

export interface GeneratedFile {
  /** Path relative to the project root, e.g. "game/generated/scenes/intro.rpy". */
  path: string;
  contents: string;
}

export function generateHeader(sourceRelPath: string): string {
  return [
    '# ==========================================================================',
    '#  GENERATED by Open-Code-RenPy-UI. DO NOT EDIT.',
    `#  Source: ${sourceRelPath}`,
    `#  Spec version: ${SPEC_VERSION}`,
    '# ==========================================================================',
    '',
  ].join('\n');
}
