import { SPEC_VERSION } from '@renpy-ui/spec';

/**
 * Uniform header for every generated .rpy file. Warns humans off manual edits
 * and records the spec source for traceability.
 */
export function generatedHeader(sourceRelPath: string): string[] {
  return [
    '# ==========================================================================',
    '#  GENERATED by Open-Code-RenPy-UI. DO NOT EDIT.',
    `#  Source: ${sourceRelPath}`,
    `#  Spec version: ${SPEC_VERSION}`,
    '# ==========================================================================',
    '',
  ];
}
